image: hrobarikt/gitpod-now-cli
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install # runs during prebuild
    cmd: npm run start:counterExample

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8081
    onOpen: open-preview  
